[package]
name = "yoti_os"
version = "0.1.0"
edition = "2021"
authors = ["YoTi <yoti1412@yandex.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
bootloader = "0.9.23"
